import { EquipmentDisplayed, EquipmentType, WeaponBaseType, PassiveType, SkillBaseType } from "./character.js";



export const emptyEquipmentDiplayed : EquipmentDisplayed = {
  ID: 1,
  Subtype: "None",
  Name: "None",
  Value: 0,

  DefensiveStats : {
    DefenseRange: 0,
    DefenseMelee: 0,
    ResPhysical: 0
  },

    Characteristics: {
      Strength: 0,
      Intelligence: 0,
      Constitution: 0,
      Charisma: 0,
      Dexterity: 0,
      Agility: 0,
      Perception: 0,
      Power: 0,
    },

  positiveBonus : "",  // all the other positive bonus provided by the equipment
  negativeBonus : "",  // all the other negative bonus provided by the equipment

}

export const emptyEquipmentBase : EquipmentType = {
  Value: 10, 
  id: 1, 
  Name: "None", 
  Subtype: "None", 
  Strength: 0, 
  Intelligence: 0, 
  Constitution: 0, 
  Charisma: 0, 
  Dexterity: 0, 
  Agility: 0, 
  Perception: 0, 
  Power: 0, 
  DefenseRange: 0, 
  DefenseMelee: 0, 
  ResPhysical: 0, 
  ResChi: 0, 
  DamChi: 0, 
  ResFire: 0, 
  DamFire: 0, 
  ResLightning: 0, 
  DamLightning: 0, 
  ResIce: 0, 
  DamIce: 0, 
  ResMental: 0, 
  DamMental: 0, 
  WeaponType: "None", 
  WeaponDamageBonus: 0, 
  WeaponPrecisionBonus: 0, 
  PrecisionRange: 0, 
  PrecisionMelee: 0, 
  HitPoint: 0, 
  Mana: 0, 
  Movement: 0, 
  Initiative: 0, 
  Nature: 0, 
  Magic: 0, 
  Demonic: 0, 
  Medecine: 0, 
  Cooking: 0, 
  Forge: 0, 
  Stealth: 0, 
  Martial: 0,
  OtherEffect: "None"
}

export const emptyWeaponBase : WeaponBaseType = {
  id: 1,
  Name: "Fist",
  Type: "Melee",
  Subtype: "Fist",
  Hand: "OneHand",
  Element: "Physical",
  Value: 265,
  BaseMinDam: 1,
  BaseMaxDam: 3,
  BasePrecision: 0,
  PrecisionRatio: 1,
  MinDamRatio: 0.8,
  MaxDamRatio: 1,
  StatDam1: "Strength",
  StatDam2: "Strength",
  StatPrecision1: "Strength",
  StatPrecision2: "Dexterity",
  CriticScore: 40,
  OtherEffects: "None"
}

export const emptyPassiveBase : PassiveType = {
  id: 1, 
  Name: "None", 
  PassiveLevel: 0, 
  LevelRequired: 1, 
  ParentPassive: 1, 
  Strength: 0, 
  Intelligence: 0, 
  Constitution: 0, 
  Charisma: 0, 
  Dexterity: 0, 
  Agility: 0, 
  Perception: 0, 
  Power: 0, 
  DefenseRange: 0, 
  DefenseMelee: 0, 
  ResPhysical: 0, 
  ResChi: 0, 
  DamChi: 0, 
  ResFire: 0, 
  DamFire: 0, 
  ResLightning: 0, 
  DamLightning: 0, 
  ResIce: 0, 
  DamIce: 0, 
  ResMental: 0, 
  DamMental: 0, 
  WeaponType: "None", 
  WeaponDamageBonus: 0, 
  WeaponPrecisionBonus: 0, 
  PrecisionRange: 0, 
  PrecisionMelee: 0, 
  HitPoint: 0, 
  Mana: 0, 
  Movement: 0, 
  Initiative: 0, 
  Nature: 0, 
  Magic: 0, 
  Demonic: 0,
  Medecine: 0, 
  Cooking: 0, 
  Forge: 0, 
  Stealth: 0, 
  Martial: 0, 
  OtherEffect: "0", 
  OtherEffectValue: 0
}

export const emptySkillBase : SkillBaseType = {
  id: 1, 
  Name: "None", 
  Type: "Range", 
  ParentSkill: 1, 
  RequiredKnowledge: "Nature", 
  KnowledgeLevel: 0, 
  SkillLevel: 0, 
  Element: "Physical", 
  ManaCost: 0, 
  ManaCostRatio: 0, 
  BaseMinDam: 0, 
  BaseMaxDam: 0, 
  BasePrecision: 0, 
  PrecisionRatio: 0, 
  MinDamRatio: 0, 
  MaxDamRatio: 0, 
  StatDam1: "Strength", 
  StatDam2: "Strength", 
  StatPrecision1: "Strength", 
  StatPrecision2: "Strength", 
  CriticScore: 40, 
  OtherEffects: "0" 
}
